src/Entity/Item.php
<?php

namespace App\Entity;

use App\Repository\ItemRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ItemRepository::class)]
class Item
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 130, unique: true)]
    private ?string $label = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 8, scale: 2)]
    private ?float $price = null;

    #[ORM\Column(nullable: false)]
    private ?int $quantity = 10;

    #[ORM\Column(length: 30, nullable: true)]
    private ?string $location = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\ManyToOne(inversedBy: 'items')]
    private ?Category $category = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(?int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }
}

src/Controller/ExoControllers2/ItemsController.php
<?php
namespace App\Controller\ExoControllers2;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class ItemsController extends AbstractController
{
    /**
     * @return Response
     */
    public function show(Request $request): Response
    {
        // Exo phase 1 - Décode JSON (request)
        $body = $request->getContent();
        $jsonArray = json_decode($body, true);
        $jsonObject = json_decode($body);
        // dd($body, $jsonArray, $jsonObject);

        // Exo phase 2 - Encode JSON (response)
        $dataArray = [
            'defaultCurrency' => 'euro',
            'promotion' => false,

            'item' => [
                'id' => 10,
                'label' => 'Fake product', 
                'price' => 9.99,
                'currency' => 'euro',
            ],
            'pack' => [
                'id' => 954,
                'price' => 250,
                'currency' => 'euro',
                'productIds' => [ 10 ],
            ]
        ];

        return $this->json($dataArray);
    }
}

src/Controller/ExoEntity3/ItemsController.php
<?php
namespace App\Controller\ExoEntity3;

use App\Entity\Item;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class ItemsController extends AbstractController
{
    public function index(ManagerRegistry $doctrine): Response
    {
        // Affichage liste des items
        $repository = $doctrine->getRepository(Item::class);
        $items = $repository->findAll();

        return $this->render('exo_entity_3/items/index.html.twig', [
            'items' => $items,
        ]);
    }

    public function create(): Response
    {
        // Affichage vue formulaire creation item
        return $this->render('exo_entity_3/items/create.html.twig');
    }

    public function store(Request $request, ManagerRegistry $doctrine): Response
    {
        // Action formulaire creation item
        
        // Entity Manager
        $entityManager = $doctrine->getManager();

        $item = new Item();
        $item->setLabel($request->request->get('label'));
        $item->setPrice($request->request->get('price'));
        $item->setQuantity($request->request->get('quantity'));
        $item->setLocation($request->request->get('location'));
        $item->setCreatedAt(new \DateTime);
        $entityManager->persist($item);
        $entityManager->flush();

        $this->addFlash('success', 'Item created !');
        return $this->redirectToRoute('entity_items_create');
    }

    public function show(ManagerRegistry $doctrine, $id): Response
    {
        // Affichage d'un seul item
        $repository = $doctrine->getRepository(Item::class);
        $item = $repository->find($id);

        if(empty($item)) {
            throw $this->createNotFoundException();
        }

        return $this->render('exo_entity_3/items/show-edit.html.twig', [
            'item' => $item,
            'edit' => false,
        ]);
    }

    public function edit(ManagerRegistry $doctrine, $id): Response
    {
        // Affichage vue formulaire de mise à jour item
        $repository = $doctrine->getRepository(Item::class);
        $item = $repository->find($id);

        if(empty($item)) {
            throw $this->createNotFoundException();
        }

        return $this->render('exo_entity_3/items/show-edit.html.twig', [
            'item' => $item,
            'edit' => true,
        ]);
    }

    public function update(Request $request, ManagerRegistry $doctrine, $id): Response
    {
        // Action formulaire de mise à jour item
        $manager = $doctrine->getManager();    
        
        $repository = $doctrine->getRepository(Item::class);
        $item = $repository->find($id);

        if(empty($item)) {
            throw $this->createNotFoundException();
        }

        $item->setLabel($request->request->get('label'));
        $item->setPrice($request->request->get('price'));
        $item->setQuantity($request->request->get('quantity'));
        $item->setLocation($request->request->get('location'));

        $manager->flush();

        $this->addFlash('success', 'Item updated !');
        return $this->redirectToRoute('entity_items_show', [
            'id' => $item->getId(),
        ]);
    }

    public function delete(ManagerRegistry $doctrine, $id): Response
    {
        // Action destruction d'un item
        $manager = $doctrine->getManager();    
        
        $repository = $doctrine->getRepository(Item::class);
        $item = $repository->find($id);

        if(empty($item)) {
            throw $this->createNotFoundException();
        }

        $manager->remove($item);
        $manager->flush();

        $this->addFlash('success', 'Item deleted !');
        return $this->redirectToRoute('entity_items_index');
    }
}

src/Controller/ExoEntity4/ItemsController.php
<?php
namespace App\Controller\ExoEntity4;

use App\Entity\Item;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class ItemsController extends AbstractController
{
    public function index(Request $request, ManagerRegistry $doctrine): Response
    {
        // Affichage liste des items
        $repository = $doctrine->getRepository(Item::class);
        $items = $repository->findByLabelAndMinimalQty(
            $request->query->get('search_list') ?: '',
            $request->query->get('qty_minimal') ?: 0,
        );

        return $this->render('exo_entity_4/items/index.html.twig', [
            'items' => $items,
        ]);
    }

    public function test(ManagerRegistry $doctrine)
    {
        // Id for the test
        $id = 3;

        // Item Repository
        /** @var ItemRepository $repository */
        $repository = $doctrine->getRepository(Item::class);

        // Find
        dd(
            $repository->findByDocQueryLang($id),
            $repository->findByNative($id),
        );

        // Delete
//        dd(
//            $repository->deleteByDocQueryLang($id),
//            $repository->deleteByNative($id),
//        );
    }
}

src/Controller/ExoEntity5/CategoriesController.php
<?php
namespace App\Controller\ExoEntity5;

use App\Entity\Category;
use App\Entity\Item;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class CategoriesController extends AbstractController
{
    public function attachItem(ManagerRegistry $doctrine, $id, $item_id)
    {
        // Entity Manager
        $entityManager = $doctrine->getManager();

        $category = $entityManager->getRepository(Category::class)->find($id);
        $item = $entityManager->getRepository(Item::class)->find($item_id);

        if (empty($category) or empty($item)) {
            $this->addFlash('error', 'The category or item is not found !');
            return $this->redirectToRoute('entity5_items_index');
        }

        // Possibilité 1: Depuis Category
        $category->addItem($item);
        $entityManager->persist($category);

        // OU Possibilité 2:  Depuis Item
//        $item->setCategory($category);
//        $entityManager->persist($item);

        $entityManager->flush();
    }

    public function detachItem(ManagerRegistry $doctrine, $id, $item_id)
    {
        // Entity Manager
        $entityManager = $doctrine->getManager();

        $category = $entityManager->getRepository(Category::class)->find($id);
        $item = $entityManager->getRepository(Item::class)->find($item_id);

        if (empty($category) or empty($item)) {
            $this->addFlash('error', 'The category or item is not found !');
            return $this->redirectToRoute('entity5_items_index');
        }

        // Possibilité 1: Depuis Category
        $category->removeItem($item);
        $entityManager->persist($category);

        // OU Possibilité 2:  Depuis Item
//        $item->setCategory(null);
//        $entityManager->persist($item);

        $entityManager->flush();
    }
}

src/Controller/ExoEntity5/ItemsController.php
<?php
namespace App\Controller\ExoEntity5;

use App\Entity\Category;
use App\Entity\Item;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class ItemsController extends AbstractController
{
    public function index(Request $request, ManagerRegistry $doctrine): Response
    {
        // Affichage liste des items
        $repository = $doctrine->getRepository(Item::class);
        $items = $repository->findByLabelAndMinimalQty(
            $request->query->get('search_list') ?: '',
            $request->query->get('qty_minimal') ?: 0,
        );

        return $this->render('exo_entity_5/items/index.html.twig', [
            'items' => $items,
        ]);
    }

    public function create(ManagerRegistry $doctrine): Response
    {
        // Affichage vue formulaire creation item
        $categories = $doctrine->getManager()
            ->getRepository(Category::class)
            ->findBy([
                'enable' => true,
            ]);

        return $this->render('exo_entity_5/items/create.html.twig', [
            'categories' => $categories,
        ]);
    }

    public function store(Request $request, ManagerRegistry $doctrine): Response
    {
        // Action formulaire creation item
        
        // Entity Manager
        $entityManager = $doctrine->getManager();

        $category = $entityManager->getRepository(Category::class)
            ->find($request->request->get('category_id'));

        if (empty($category)) {
            $this->addFlash('error', 'The category is not found !');
            return $this->redirectToRoute('entity5_items_create');
        }

        $item = new Item();
        $item->setLabel($request->request->get('label'));
        $item->setPrice($request->request->get('price'));
        $item->setQuantity($request->request->get('quantity'));
        $item->setLocation($request->request->get('location'));
        $item->setCreatedAt(new \DateTime);
        $item->setCategory($category);
        $entityManager->persist($item);
        $entityManager->flush();

        $this->addFlash('success', 'Item created !');
        return $this->redirectToRoute('entity5_items_index');
    }

    public function attachCategory(ManagerRegistry $doctrine, $id, $category_id)
    {
        // Entity Manager
        $entityManager = $doctrine->getManager();

        $category = $entityManager->getRepository(Category::class)->find($category_id);
        $item = $entityManager->getRepository(Item::class)->find($id);

        if (empty($category) or empty($item)) {
            $this->addFlash('error', 'The category or item is not found !');
            return $this->redirectToRoute('entity5_items_index');
        }

        // Possibilité 1: Depuis Category
//        $category->addItem($item);
//        $entityManager->persist($category);

        // OU Possibilité 2:  Depuis Item
        $item->setCategory($category);
        $entityManager->persist($item);

        $entityManager->flush();
    }

    public function detachCategory(ManagerRegistry $doctrine, $id)
    {
        // Entity Manager
        $entityManager = $doctrine->getManager();

        $item = $entityManager->getRepository(Item::class)->find($id);

        if (empty($item)) {
            $this->addFlash('error', 'The item is not found !');
            return $this->redirectToRoute('entity5_items_index');
        }

        $item->setCategory(null);
        $entityManager->persist($item);

        $entityManager->flush();
    }
}

src/Controller/ExoTwig1/ItemsController.php
<?php
namespace App\Controller\ExoTwig1;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class ItemsController extends AbstractController
{
    /**
     * @param Request $request
     * @return Response
     */
    public function index(Request $request): Response
    {
        $extendValueTestableArray = [
            'key1' => 'value1',
            'key2' => 'value2',
            'key3' => 'value3',
        ];

        return $this->render('/exo_twig1/items/index.html.twig', [
            'items' => $extendValueTestableArray,
            'display' => $request->get('display'), // Ou $request->query->get('display')
            'tableJson' => json_encode($extendValueTestableArray),
        ]);
    }
}

templates/exo_entity_5/items/create.html.twig
{% extends "layouts/app.html.twig" %}

{% block title %}Items Create{% endblock %}

{% block content %}
    <form method="POST" action="{{ path('entity5_items_store') }}">
        <label for="category-id">Category</label><br>
        <select name="category_id" id="category-id">
            <option value="" selected disabled>Choose</option>

            {% for category in categories %}
                <option value="{{ category.id }}">{{ category.name|upper }}</option>
            {% endfor %}
        </select>

        <br>
        <label for="label">Label</label><br>
        <input type="text" name="label" id="label">

        <br>
        <label for="price">Price</label><br>
        <input type="number" name="price" id="price">

        <br>
        <label for="quantity">Quantity</label><br>
        <input type="number" name="quantity" id="quantity">

        <br>
        <label for="location">Location</label><br>
        <input type="text" name="location" id="location">
        
        <br>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

templates/exo_entity_5/items/index.html.twig
{% extends "layouts/app.html.twig" %}

{% block title %}Items List{% endblock %}

{% block content %}
    <section>
        <form action="{{ path('entity5_items_index') }}">
            <label for="search-list">Search:</label><br>
            <input type="search" name="search_list" id="search-list" value="{{ app.request.get('search_list') }}">

            <br>
            <label for="qty-minimal">Minimal quantity:</label><br>
            <input type="number" name="qty_minimal" id="qty-minimal" placeholder="0" value="{{ app.request.get('qty_minimal') }}">

            <br>
            <input type="submit" value="Search">
            <br><br>
        </form>
    </section>

    <section>
        <a class="btn" href="{{ path('entity5_items_create') }}">Create a new Item</a>
    </section>

    <section>
        <table class="pretty-table">
            <tr>
                <th>Id</th>
                <th>Label</th>
                <th>Price</th>
                <th>Qty</th>
                <th>Location</th>
                <th>Created At</th>
                <th>Actions</th>
            </tr>
            {% for item in items %}
                <tr>
                    <td>{{item.id}}</td>
                    <td>{{item.label}}</td>
                    <td>{{item.price}}</td>
                    <td>{{item.quantity}}</td>
                    <td>{{item.location}}</td>
                    <td class="inner-date" data-value="{{ item.createdAt|date('U') }}"></td>
                    <td>
                        <a class="btn btn-very-flat" href="{{ path('entity_items_show', {id: item.id}) }}">Show</a>
                        <br>
                        <a class="btn btn-very-flat bg-orange" href="{{ path('entity_items_edit', {id: item.id}) }}">Edit</a>
                        <br>
                        <a class="btn btn-very-flat bg-red" href="{{ path('entity_items_delete', {id: item.id}) }}">Direct delete</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </section>
{% endblock %}

{% block script_body %}
    <script>

        function translateDate(selector) {
            const inputDate = document
                .querySelectorAll(selector)
                .forEach(el => {
                    el.innerHTML = '';

                    const unixTimestramps = parseInt(el.getAttribute('data-value')) * 1000;
                    if (unixTimestramps) {
                        const date = new Date(unixTimestramps);
                        el.innerHTML = date.toLocaleDateString();
                    }
                });
        }

        translateDate('.inner-date');
    </script>
{% endblock %}

templates/exo_entity_5/items/show-edit.html.twig
{% extends "layouts/app.html.twig" %}

{% block title %}Items {{ edit ? 'Edit' : 'Show' }}{% endblock %}

{% block content %}
    <form method="POST" action="{{ edit ? path('entity_items_update', {id: item.id}) : '' }}">
        <label for="label">Label</label><br>
        <input type="text" name="label" id="label" 
            value="{{ item.label }}" 
            {{ edit ? '' : 'disabled' }}
            class="input-label {{ edit ? 'input-edit' : 'input-show' }}"
        >

        <br>
        <label for="price">Price</label><br>
        <input type="number" name="price" id="price" 
            value="{{ item.price }}"
            {{ edit ? '' : 'disabled' }}
            class="input-label {{ edit ? 'input-edit' : 'input-show' }}"
        >

        <br>
        <label for="quantity">Quantity</label><br>
        <input type="number" name="quantity" id="quantity" 
            value="{{ item.quantity }}"
            {{ edit ? '' : 'disabled' }}
            class="input-label {{ edit ? 'input-edit' : 'input-show' }}"
        >

        <br>
        <label for="location">Location</label><br>
        <input type="text" name="location" id="location" 
            value="{{ item.location }}"{{ edit ? '' : 'disabled' }}
            class="input-label {{ edit ? 'input-edit' : 'input-show' }}"
        >
        
        {% if edit %}
            <br><br>
            <input type="submit" value="Update the Item">

            <p>
                <a href="{{ path('entity_items_show', {id: item.id}) }}">Return to Show</a>
            </p>
        {% else %}
            <p>
                <a href="{{ path('entity_items_edit', {id: item.id}) }}">Go to Edit</a>
            </p>
            <p>
                <a href="{{ path('entity_items_delete', {id: item.id}) }}">Direct delete</a>
            </p>
        {% endif %}
    </form>
{% endblock %}